#config_version=5

# Taxonomy:
# Switches, coils, and other devices are prefaced with a unique letter or combination of letters,,
# followed by the device name, followed by position, then finally any modifier.
# Essentially they go from least to most specific

coils:
  c_flipper_left_main:
    number: 0-0
    #default_pulse_ms: 10
    label: "Left Flipper"
  c_flipper_left_hold:
    number: 0-1
    #default_hold_power: 1.0
    allow_enable: true
    label: "Left Flipper Hold"
  c_flipper_right_main:
    number: 0-2
    #default_pulse_ms: 10
    label: "Right Flipper"
  c_flipper_right_hold:
    number: 0-3
    #default_hold_power: 1.0
    allow_enable: true
    label: "Right Flipper Hold"
  c_trough_eject:
    number: 0-4
    label: "Ball Trough Eject"
  c_autokicker:
    number: 0-5
    label: "Auto Kicker"
  c_slingshot_left:
    number: 0-6
    label: "Left Slingshot"
  c_slingshot_right:
    number: 0-7
    label: "Right Slingshot"
  c_pop_1:
    number:
    label: "Popbumper 1"
