#config_version=5

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: com4, com5

config:
  - switches.yaml
  - coils.yaml
  - flippers.yaml
  - autofires.yaml
  - ball_devices.yaml
  - playfields.yaml
  - droptargets.yaml
  - displays.yaml
  - lights.yaml
  - pololu-maestro.yaml
  - dmd.yaml
  - slides.yaml
  - modes.yaml
  - keyboard.yaml
 

