#config_version=4

hardware:
  platform: fast
  driverboards: fast

fast:
  # ports are determined by `ls /dev/tty.*` and will be something like tty.usbserial-141A
  # for nano controller, use the two middle ports
  ports: /dev/ttyUSB1, /dev/ttyUSB2
  
  # Watchdog will kill Fast controller power if it can't talk to MPF
  # watchdog setting in ms, default 1000, use 0 to disable
#  watchdog: 1000

#  default_quick_debounce_open: 2ms
#  default_quick_debounce_close: 2ms
#  default_normal_debounce_open: 10ms
#  default_normal_debounce_close: 10ms

  # Turn on hardware debugging. Warning: generates large logfiles quickly!
  debug: true


switches:
  s_left_flipper:
    # Fast hardware switches are <board>-<switch>, starting at 0 for both
    number: 0-0
    # custom per-switch debounce_time: 0-255 (ms), how long new state must be set before event fires off
    #debounce_open: 12
    #debounce_close: 6

#  s_right_flipper:
#    number: 

# Fast Power Settings
# pulse and hold power levels map to 8-bit PWM masks as follows:
# 0: 00000000 (or 0%)
# 1: 00000001 (or 12%)
# 2: 10001000 (25%)
# 3: 10010010 (37.5%)
# 4: 10101010 (50%)
# 5: 10111010 (62.5%)
# 6: 11101110 (75%)
# 7: 11111110 (87.5%)
# 8: 11111111 (100%)

coils:
  c_left_flipper:
    # Fast hardware coils are <board>-<coil>, starting at 0 for both
    number: 0-0

    # allow flipper to be held in on position
#    allow_enable: true

    # hold power uses Fast power settings values 
    #hold_pwm_mask: 11001100
#    hold_power: 2

    # pulse control (same as hold power, plus duration)
    #pulse_pwm_mask: 11001100
    pulse_power: 4
    pulse_ms: 30

    #recycle defines a cool-down equal to twice the pulse_ms value by default
    #recycle: true
    #specifying a recycle_ms time overrides the recycle: setting
    #recycle_ms: 100

#  c_right_flipper:
#    number: 

flippers:
  left_flipper:
    main_coil: c_left_flipper
    activation_switch: s_left_flipper
    # allow flipper to actuate at any time, not just when a ball is active
    enable_events: machine_reset_phase_3

#  right_flipper:
#    main_coil: c_right_flipper
#    activation_switch: s_right_flipper
   
