hardware:
  rgb-dmd: smartmatrix

smartmatrix:
  dmd:
    port: com7
    baud: 2500000
    old_cookie: true

rgb_dmds:
  dmd:
    hardware_brightness: 0.3
    fps: 20
    source_display: dmd

displays:
  dmd:
    width: 128
    height: 32
    default: true
