#config_version=5

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right
    enable_events: machine_reset_phase_3
