#config_version=5

mode:
  start_events: ball_starting
  stop_events: pop_level1_done
  priority: 1000

variable_player:
  s_pop1_active:
    score: 100
  s_pop2_active:
    score: 100
  s_pop3_active:
    score: 100

counters:
  pop1_level1:
    count_events: s_pop1_active
    starting_count: 0
    count_complete_value: 7
    direction: up
  pop2_level1:
    count_events: s_pop2_active
    starting_count: 0
    count_complete_value: 7
    direction: up
  pop3_level1:
    count_events: s_pop3_active
    starting_count: 0
    count_complete_value: 7
    direction: up

show_player:
  mode_pop_leve1_started:
    pop_upgrade:
      pop: pop1
    pop_upgrade:
      pop: pop2
    pop_upgrade:
      pop: pop3
  logicblock_pop1_level1_updated:
    pop_upgrade:
      start_step: device.counters.pop1_level1["value"] + 1
      pop: pop1
      color: d8bfd8
  logicblock_pop2_level1_updated:
    pop_upgrade:
      start_step: device.counters.pop2_level1["value"] + 1
      pop: pop2
      color: d8bfd8
  logicblock_pop3_level1_updated:
    pop_upgrade:
      start_step: device.counters.pop3_level1["value"] + 1
      pop: pop3
      color: d8bfd8

accruals:
  pop_level1:
    events:
      - logicblock_pop1_level1_complete
      - logicblock_pop2_level1_complete
      - logicblock_pop3_level1_complete
    events_when_complete: pop_level1_done
